import torch
import torch.nn as nn
from transformers import PreTrainedModel, AutoConfig, AutoModel, LogitsProcessorList, StoppingCriteriaList
import torch.nn.functional as F
from typing import Optional, Union, Callable
import numpy as np
import time
import math
from typing import List, Dict, Any

try:
    from transformers import WatermarkingConfig, WatermarkLogitsProcessor
except ImportError:
    WatermarkingConfig = None
    WatermarkLogitsProcessor = None

from .configuration_diffusion import DiffusionConfig

def get_num_transfer_tokens(mask_index, steps, schedule="linear"):
    """
    Compute the number of tokens to unmask at each step for each sequence in the batch.
    """
    mask_num = mask_index.sum(dim=1)  # Shape: (batch_size,)

    fractions = torch.zeros(steps, dtype=torch.float32, device=mask_index.device)
    for i in range(steps):
        x = (i + 1) / steps
        if schedule == "cosine":
            frac = math.sin(x * math.pi / 2)
        elif schedule == "square":
            frac = x ** 2
        elif schedule == "exponential":
            frac = (math.exp(3 * x) - 1) / (math.exp(3) - 1)
        elif schedule == "sigmoid":
            val = 1 / (1 + math.exp(-10 * (x - 0.5)))
            min_val = 1 / (1 + math.exp(5))
            max_val = 1 / (1 + math.exp(-5))
            frac = (val - min_val) / (max_val - min_val)
        else: # linear or fallback
            frac = x
        fractions[i] = frac

    target_unmasked = torch.round(mask_num.unsqueeze(1).float() * fractions.unsqueeze(0)).long()

    prev_unmasked = torch.cat([torch.zeros_like(mask_num.unsqueeze(1)), target_unmasked[:, :-1]], dim=1)

    transfer_tokens = target_unmasked - prev_unmasked
    return transfer_tokens

def filter_special_tokens(tokens, tokenizer, mask_id):
    """
    Replace special tokens generated by the model with mask_id.
    """
    special_ids = [tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id]
    special_ids = [id for id in special_ids if id is not None]

    mask = torch.zeros_like(tokens, dtype=torch.bool)
    for special_id in special_ids:
        mask |= (tokens == special_id)

    tokens = torch.where(mask, torch.tensor(mask_id, device=tokens.device, dtype=tokens.dtype), tokens)
    return tokens

class DiffusionModelForConditionalGeneration(PreTrainedModel):
    config_class = DiffusionConfig

    def __init__(self, config: DiffusionConfig):
        super().__init__(config)

        base_config = AutoConfig.for_model(**config.base_config_dict)
        if getattr(config, "use_sdpa", False):
            base_config._attn_implementation = "sdpa"
        self.inner_model = AutoModel.from_config(base_config)
        self._disable_causal_mask()

        self.timestep_embedder = nn.Sequential(
            nn.Linear(1, config.timestep_dim),
            nn.SiLU(),
            nn.Linear(config.timestep_dim, base_config.hidden_size)
        )

        self.lm_head = nn.Linear(base_config.hidden_size, base_config.vocab_size, bias=False)

        if getattr(base_config, "tie_word_embeddings", False):
            self.lm_head.weight = self.inner_model.get_input_embeddings().weight

    def _disable_causal_mask(self):
        """
        Dynamic patching to disable causality.
        In transformers >= 5.9.0, masking is delegated to masking_utils which
        checks config.is_causal. Setting it to False allows fallback to
        bidirectional mask.
        For older models or specific implementations, further patching can be done.
        """
        if hasattr(self.inner_model, "config"):
            self.inner_model.config.is_causal = False

        # Additionally patch _update_causal_mask if present (from the example)
        if hasattr(self.inner_model, "_update_causal_mask"):
            self.inner_model._update_causal_mask = lambda *args, **kwargs: args[1] if len(args) > 1 else kwargs.get("attention_mask")

        if self.inner_model.config.model_type == "gpt2":
            for module in self.inner_model.modules():
                if hasattr(module, "bias") and isinstance(module.bias, torch.Tensor) and module.bias.dim() == 4:
                    module.bias.data.fill_(1)


    def get_steering_vector(self, positive_input_ids, negative_input_ids, layer_name, attention_mask=None):
        captured_states = []

        def hook(module, input, output):
            if isinstance(output, tuple):
                captured_states.append(output[0].detach())
            else:
                captured_states.append(output.detach())

        target_layer = dict(self.inner_model.named_modules()).get(layer_name)
        if target_layer is None:
            raise ValueError(f"Layer {layer_name} not found in inner_model")

        handle = target_layer.register_forward_hook(hook)

        try:
            self.forward(input_ids=positive_input_ids, attention_mask=attention_mask)
            self.forward(input_ids=negative_input_ids, attention_mask=attention_mask)
        finally:
            handle.remove()

        if len(captured_states) != 2:
            raise RuntimeError("Failed to capture hidden states for both forward passes.")

        positive_mean = captured_states[0].mean(dim=1)
        negative_mean = captured_states[1].mean(dim=1)

        return positive_mean - negative_mean

    def get_input_embeddings(self):
        return self.inner_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.inner_model.set_input_embeddings(value)

    def forward(self, input_ids=None, timesteps=None, attention_mask=None, inputs_embeds=None, labels=None, steering_vector=None, steering_layer_name=None, steering_scale=1.0, **kwargs):
        if inputs_embeds is None:
            if input_ids is None:
                raise ValueError("You have to specify either input_ids or inputs_embeds")
            embeddings_layer = self.inner_model.get_input_embeddings()
            inputs_embeds = embeddings_layer(input_ids)

        if timesteps is not None:
            t_embed = self.timestep_embedder(timesteps.unsqueeze(-1).float())
            hidden_states = inputs_embeds + t_embed.unsqueeze(1)
        else:
            hidden_states = inputs_embeds

        handle = None
        if steering_vector is not None and steering_layer_name is not None:
            target_layer = dict(self.inner_model.named_modules()).get(steering_layer_name)
            if target_layer is not None:
                def steer_hook(module, input, output):
                    steer = steering_scale * steering_vector.unsqueeze(1) # shape (batch, 1, hidden)
                    if isinstance(output, tuple):
                        return tuple([output[0] + steer] + list(output[1:]))
                    return output + steer
                handle = target_layer.register_forward_hook(steer_hook)

        try:
            inner_kwargs = kwargs.copy()
            if 'return_dict' in inner_kwargs:
                del inner_kwargs['return_dict']
            outputs = self.inner_model(
                inputs_embeds=hidden_states,
                attention_mask=attention_mask,
                return_dict=True,
                **inner_kwargs
            )
        finally:
            if handle is not None:
                handle.remove()

        logits = self.lm_head(outputs.last_hidden_state)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            # Shift so that tokens < n predict n - we don't do this for diffusion
            # Calculate loss only on positions where labels != -100 (which corresponds to masked positions)
            loss = loss_fct(logits.view(-1, self.config.base_config_dict.get('vocab_size', logits.size(-1))), labels.view(-1))

        return_dict = kwargs.get('return_dict', True)
        if return_dict:
            from transformers.modeling_outputs import CausalLMOutputWithPast
            return CausalLMOutputWithPast(
                loss=loss,
                logits=logits,
                past_key_values=outputs.past_key_values if hasattr(outputs, "past_key_values") else None,
                hidden_states=outputs.hidden_states if hasattr(outputs, "hidden_states") else None,
                attentions=outputs.attentions if hasattr(outputs, "attentions") else None,
            )
        else:
            return tuple(v for v in [loss, logits] if v is not None)

    @torch.no_grad()
    def generate(
        self,
        input_ids: torch.Tensor,
        max_new_tokens: Optional[int] = None,
        max_length: Optional[int] = None,
        min_length: Optional[int] = None,
        min_new_tokens: Optional[int] = None,
        steps: Optional[int] = None,
        block_length: Optional[int] = None,
        temperature: float = 0.0,
        temperature_schedule: str = "constant",
        min_temperature: float = 0.0,
        gumbel_temperature: Optional[float] = None,
        gumbel_temperature_schedule: str = "constant",
        min_gumbel_temperature: float = 0.0,
        cfg_scale: float = 0.0,
        cfg_schedule: str = "constant",
        guidance_rescale: float = 0.0,
        guidance_rescale_schedule: str = "constant",
        min_guidance_rescale: float = 0.0,
        top_k: int = 0,
        top_k_schedule: str = "constant",
        min_top_k: int = 0,
        top_p: float = 1.0,
        top_p_schedule: str = "constant",
        min_top_p: float = 0.0,
        min_p: float = 0.0,
        min_p_schedule: str = "constant",
        min_min_p: float = 0.0,
        typical_p: float = 1.0,
        typical_p_schedule: str = "constant",
        min_typical_p: float = 0.0,
        top_a: float = 0.0,
        top_a_schedule: str = "constant",
        min_top_a: float = 0.0,
        epsilon_cutoff: float = 0.0,
        epsilon_cutoff_schedule: str = "constant",
        min_epsilon_cutoff: float = 0.0,
        eta_cutoff: float = 0.0,
        eta_cutoff_schedule: str = "constant",
        min_eta_cutoff: float = 0.0,
        tfs_z: float = 1.0,
        tfs_z_schedule: str = "constant",
        min_tfs_z: float = 1.0,
        top_n_tokens: int = 0,
        top_n_tokens_schedule: str = "constant",
        min_top_n_tokens: int = 0,
        dynamic_temperature_entropy: float = 0.0,
        dynamic_temperature_entropy_schedule: str = "constant",
        min_dynamic_temperature_entropy: float = 0.0,
        encoder_repetition_penalty: float = 1.0,
        encoder_frequency_penalty: float = 0.0,
        encoder_presence_penalty: float = 0.0,
        repetition_penalty: float = 1.0,
        repetition_penalty_schedule: str = "constant",
        min_repetition_penalty: float = 1.0,
        frequency_penalty: float = 0.0,
        frequency_penalty_schedule: str = "constant",
        min_frequency_penalty: float = 0.0,
        presence_penalty: float = 0.0,
        presence_penalty_schedule: str = "constant",
        min_presence_penalty: float = 0.0,
        length_penalty: float = 1.0,
        length_penalty_schedule: str = "constant",
        min_length_penalty: float = 1.0,
        penalty_range: Optional[int] = None,
        logit_smoothing: float = 0.0,
        xtc_threshold: float = 0.0,
        xtc_threshold_schedule: str = "constant",
        min_xtc_threshold: float = 0.0,
        xtc_probability: float = 0.0,
        xtc_probability_schedule: str = "constant",
        min_xtc_probability: float = 0.0,
        tkg_scale: float = 0.0,
        tkg_schedule: str = "constant",
        tkg_min_scale: float = 0.0,
        encoder_no_repeat_ngram_size: int = 0,
        no_repeat_ngram_size: int = 0,
        ngram_penalty: float = 1.0,
        ngram_size: int = 0,
        temperature_mask: Optional[torch.Tensor] = None,
        bad_words_ids: Optional[list[list[int]]] = None,
        max_time: Optional[float] = None,
        remove_invalid_values: bool = False,
        logit_bias: Optional[dict[int, float]] = None,
        suppress_tokens: Optional[list[int]] = None,
        begin_suppress_tokens: Optional[list[int]] = None,
        remasking: Optional[str] = None,
        attention_mask: Optional[torch.Tensor] = None,
        unconditional_input_ids: Optional[torch.Tensor] = None,
        negative_prompt_ids: Optional[torch.Tensor] = None,
        steering_vector: Optional[torch.Tensor] = None,
        steering_layer_name: Optional[str] = None,
        steering_scale: float = 1.0,
        eos_token_id: Optional[Union[int, list[int]]] = None,
        pad_token_id: Optional[int] = None,
        forced_decoder_ids: Optional[list[list[int]]] = None,
        forced_eos_token_id: Optional[Union[int, list[int]]] = None,
        renormalize_logits: bool = False,

        unmasking_schedule: str = "linear",
        num_beams: int = 1,
        classifier_fn: Optional[Callable] = None,

        classifier_scale: float = 0.0,
        classifier_schedule: str = "constant",
        min_classifier_scale: float = 0.0,
        num_return_sequences: int = 1,
        return_dict_in_generate: bool = False,
        output_scores: bool = False,
        logits_processor: Optional[LogitsProcessorList] = None,
        stopping_criteria: Optional[StoppingCriteriaList] = None,
        watermarking_config: Optional[Union[dict, 'WatermarkingConfig']] = None,
        draft_model: Optional["PreTrainedModel"] = None,
        speculative_steps: int = 1,
        speculative_threshold: float = 0.5,
        **kwargs
    ):
        """
        Iterative unmasking generation for Diffusion Models.
        """
        start_time = time.time() if max_time is not None else None

        if negative_prompt_ids is not None:
            unconditional_input_ids = negative_prompt_ids

        original_batch_size = input_ids.size(0)
        batch_multiplier = num_beams if num_beams > 1 else num_return_sequences

        if batch_multiplier > 1:
            input_ids = input_ids.repeat_interleave(batch_multiplier, dim=0)
            if attention_mask is not None:
                attention_mask = attention_mask.repeat_interleave(batch_multiplier, dim=0)
            if unconditional_input_ids is not None:
                unconditional_input_ids = unconditional_input_ids.repeat_interleave(batch_multiplier, dim=0)
            if negative_prompt_ids is not None:
                negative_prompt_ids = negative_prompt_ids.repeat_interleave(batch_multiplier, dim=0)
        batch_size = input_ids.size(0)

        steps = steps or self.config.diffusion_steps
        block_length = block_length or self.config.block_size
        remasking = remasking or self.config.remasking_strategy
        mask_id = self.config.mask_token_id

        if mask_id is None:
            raise ValueError("mask_token_id must be set in the configuration for generation.")

        T = input_ids.size(-1)
        device, dtype = input_ids.device, input_ids.dtype

        if max_length is not None and max_new_tokens is None:
            max_new_tokens = max(0, max_length - T)
        elif max_length is not None and max_new_tokens is not None:
            max_new_tokens = min(max_new_tokens, max(0, max_length - T))
        elif max_new_tokens is None:
            max_new_tokens = 128

        if min_length is not None:
            min_new_tokens = max(min_new_tokens or 0, min_length - T)

        if max_new_tokens > 0 and max_new_tokens % block_length != 0:
            block_length = max_new_tokens

        num_blocks = max_new_tokens // block_length if max_new_tokens > 0 else 0
        if num_blocks > 0:
            if steps % num_blocks != 0:
                steps_per_block = max(1, steps // num_blocks)
            else:
                steps_per_block = steps // num_blocks
        else:
            steps_per_block = steps

        x = torch.full((batch_size, T + max_new_tokens), mask_id, dtype=dtype, device=device)
        x[:, :T] = input_ids

        if num_beams > 1:
            beam_scores = torch.zeros((original_batch_size, num_beams), dtype=torch.float, device=device)
            beam_scores[:, 1:] = -1e9
            beam_scores = beam_scores.view(-1)

        if forced_decoder_ids is not None:
            for forced_id in forced_decoder_ids:
                if len(forced_id) == 2:
                    idx, token = forced_id
                    if 0 <= idx < max_new_tokens:
                        x[:, T + idx] = token

        if forced_eos_token_id is not None:
            if isinstance(forced_eos_token_id, list):
                x[:, T + max_new_tokens - 1] = forced_eos_token_id[0]
            else:
                x[:, T + max_new_tokens - 1] = forced_eos_token_id

        scores = [] if return_dict_in_generate and output_scores else None

        watermark_processor = None

        for num_block in range(num_blocks):
            if max_time is not None and time.time() - start_time > max_time:
                break

            block_start = T + num_block * block_length
            block_end = T + (num_block + 1) * block_length

            block_mask_index = (x[:, block_start:block_end] == mask_id)
            num_transfer_tokens = get_num_transfer_tokens(block_mask_index, steps_per_block, schedule=unmasking_schedule)

            for i in range(steps_per_block):
                if max_time is not None and time.time() - start_time > max_time:
                    break

                step_ratio = i / max(1, steps_per_block - 1) if steps_per_block > 1 else 0.0

                mask_index = (x == mask_id)

                # We can supply timesteps if needed, but in basic sampling they are implicit or t=0 for unmasked
                # A simple approximation: timesteps is proportional to remaining masks
                t_ratio = mask_index.sum(dim=1).float() / (T + max_new_tokens)
                current_timesteps = (t_ratio * self.config.max_timesteps).long().clamp(min=1, max=self.config.max_timesteps)

                draft_mask_index = None
                spec_tokens = None
                if draft_model is not None:
                    # Run draft model to get candidate tokens
                    draft_outputs = draft_model(
                        input_ids=x,
                        attention_mask=attention_mask,
                        timesteps=current_timesteps,
                        steering_vector=steering_vector,
                        steering_layer_name=steering_layer_name,
                        steering_scale=steering_scale
                    )
                    draft_logits = draft_outputs.logits if hasattr(draft_outputs, "logits") else draft_outputs[0]

                    # Unmask speculative_steps * N tokens using draft_model
                    draft_probs = torch.nn.functional.softmax(draft_logits.to(torch.float64), dim=-1)
                    draft_confidence = -(-torch.sum(draft_probs * torch.log(draft_probs + 1e-9), dim=-1))

                    draft_x0 = torch.argmax(draft_logits, dim=-1)
                    if hasattr(self, 'tokenizer') and self.tokenizer is not None:
                        draft_x0 = filter_special_tokens(draft_x0, self.tokenizer, mask_id)

                    draft_confidence = torch.where(mask_index, draft_confidence, -torch.tensor(float('inf'), device=device, dtype=torch.float64))

                    draft_mask_index = mask_index.clone()
                    spec_tokens = torch.zeros_like(x, dtype=torch.bool, device=device)

                    for j in range(x.shape[0]):
                        M_draft = min(num_transfer_tokens[j, i].item() * speculative_steps, mask_index[j].sum().item())
                        if M_draft > 0:
                            _, draft_select_index = torch.topk(draft_confidence[j], k=M_draft)
                            spec_tokens[j, draft_select_index] = True
                            x[j, draft_select_index] = draft_x0[j, draft_select_index].to(x.dtype)

                outputs = self(
                    input_ids=x,
                    attention_mask=attention_mask,
                    timesteps=current_timesteps,
                    steering_vector=steering_vector,
                    steering_layer_name=steering_layer_name,
                    steering_scale=steering_scale
                )
                logits = outputs.logits if hasattr(outputs, "logits") else outputs[0]

                if draft_model is not None:
                    # Verification step
                    target_probs = torch.nn.functional.softmax(logits.to(torch.float64), dim=-1)
                    target_x0 = torch.argmax(logits, dim=-1)

                    for j in range(x.shape[0]):
                        for pos in range(x.shape[1]):
                            if spec_tokens[j, pos]:
                                token_draft = x[j, pos]
                                prob_target = target_probs[j, pos, token_draft].item()

                                if prob_target >= speculative_threshold or token_draft == target_x0[j, pos]:
                                    # Accept
                                    pass
                                else:
                                    # Reject, revert to target model prediction or mask
                                    x[j, pos] = target_x0[j, pos].to(x.dtype)
                                    # Effectively, we treat it as if target model predicted it this step,
                                    # or we can mask it back if we want strictly iterative:
                                    # x[j, pos] = mask_id

                    # We continue with normal generation steps (logits modification, etc)
                    # But since we already modified x, we might need to adjust mask_index
                    mask_index = (x == mask_id)


                if watermarking_config is not None and WatermarkLogitsProcessor is not None:
                    if watermark_processor is None:
                        watermark_kwargs = watermarking_config if isinstance(watermarking_config, dict) else vars(watermarking_config)
                        watermark_processor = WatermarkLogitsProcessor(vocab_size=logits.size(-1), device=logits.device, **watermark_kwargs)

                    mask_positions = mask_index.nonzero(as_tuple=True)
                    if len(mask_positions[0]) > 0:
                        context_width = watermark_kwargs.get("context_width", 1)
                        pseudo_input_ids = []
                        pseudo_scores = []
                        valid_indices = []

                        for b, s in zip(mask_positions[0], mask_positions[1]):
                            if s >= context_width:
                                pseudo_input_ids.append(x[b, s - context_width:s])
                                pseudo_scores.append(logits[b, s])
                                valid_indices.append((b, s))

                        if len(pseudo_input_ids) > 0:
                            pseudo_input_ids = torch.stack(pseudo_input_ids)
                            pseudo_scores = torch.stack(pseudo_scores)

                            new_pseudo_scores = watermark_processor(pseudo_input_ids, pseudo_scores)

                            for i, (b, s) in enumerate(valid_indices):
                                logits[b, s] = new_pseudo_scores[i]

                if remove_invalid_values:
                    # set all nan values to 0.0
                    logits = torch.where(logits != logits, 0.0, logits)
                    # set all +/-inf values to max/min possible value
                    logits = torch.where(logits == float("inf"), torch.finfo(logits.dtype).max, logits)
                    logits = torch.where(logits == -float("inf"), torch.finfo(logits.dtype).min, logits)

                current_top_k = top_k
                if top_k > 0:
                    if top_k_schedule == "linear":
                        current_top_k = int(top_k * (1.0 - step_ratio))
                    elif top_k_schedule == "cosine":
                        current_top_k = int(top_k * 0.5 * (1.0 + math.cos(math.pi * step_ratio)))
                    elif top_k_schedule == "exponential":
                        current_top_k = int(top_k * math.exp(-3.0 * step_ratio))
                    elif top_k_schedule == "cyclic":
                        current_top_k = int(top_k * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio)))
                    current_top_k = max(current_top_k, min_top_k)

                if (cfg_scale > 0.0 or tkg_scale > 0.0) and unconditional_input_ids is not None:
                    uncond_x = x.clone()
                    # Replace the conditional prefix with unconditional prefix
                    uncond_len = unconditional_input_ids.size(1)
                    uncond_x[:, :uncond_len] = unconditional_input_ids

                    uncond_outputs = self(
                        input_ids=uncond_x,
                        attention_mask=attention_mask,
                        timesteps=current_timesteps,
                        steering_vector=steering_vector,
                        steering_layer_name=steering_layer_name,
                        steering_scale=steering_scale
                    )
                    uncond_logits = uncond_outputs.logits if hasattr(uncond_outputs, "logits") else uncond_outputs[0]

                    guided_logits = logits.clone()

                    if cfg_scale > 0.0:
                        if cfg_schedule == "linear":
                            current_cfg_scale = cfg_scale * (1.0 - step_ratio)
                        elif cfg_schedule == "cosine":
                            current_cfg_scale = cfg_scale * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                        elif cfg_schedule == "exponential":
                            current_cfg_scale = cfg_scale * math.exp(-3.0 * step_ratio)
                        elif cfg_schedule == "cyclic":
                            current_cfg_scale = cfg_scale * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                        else:
                            current_cfg_scale = cfg_scale

                        guided_logits = uncond_logits + current_cfg_scale * (logits - uncond_logits)

                    if tkg_scale > 0.0 and current_top_k > 0:
                        if tkg_schedule == "linear":
                            current_tkg_scale = tkg_scale * (1.0 - step_ratio)
                        elif tkg_schedule == "cosine":
                            current_tkg_scale = tkg_scale * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                        elif tkg_schedule == "exponential":
                            current_tkg_scale = tkg_scale * math.exp(-3.0 * step_ratio)
                        elif tkg_schedule == "cyclic":
                            current_tkg_scale = tkg_scale * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                        else:
                            current_tkg_scale = tkg_scale

                        current_tkg_scale = max(current_tkg_scale, tkg_min_scale)

                        top_k_val = min(max(current_top_k, 1), logits.size(-1))
                        top_k_thresholds = torch.topk(logits, top_k_val, dim=-1)[0][..., -1, None]
                        mask = logits >= top_k_thresholds
                        guided_logits = guided_logits + current_tkg_scale * (logits - uncond_logits) * mask.float()

                    if guidance_rescale > 0.0 and (cfg_scale > 0.0 or tkg_scale > 0.0):
                        if guidance_rescale_schedule == "linear":
                            current_guidance_rescale = guidance_rescale * (1.0 - step_ratio)
                        elif guidance_rescale_schedule == "cosine":
                            current_guidance_rescale = guidance_rescale * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                        elif guidance_rescale_schedule == "exponential":
                            current_guidance_rescale = guidance_rescale * math.exp(-3.0 * step_ratio)
                        elif guidance_rescale_schedule == "cyclic":
                            current_guidance_rescale = guidance_rescale * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                        else:
                            current_guidance_rescale = guidance_rescale

                        current_guidance_rescale = max(current_guidance_rescale, min_guidance_rescale)

                        std_logits = logits.std(dim=-1, keepdim=True)
                        std_guided_logits = guided_logits.std(dim=-1, keepdim=True)
                        # Fix out of bounds if standard deviation is exactly 0 to avoid NaNs
                        std_guided_logits = torch.where(std_guided_logits > 0, std_guided_logits, torch.ones_like(std_guided_logits))

                        guided_logits_rescaled = guided_logits * (std_logits / std_guided_logits)
                        guided_logits = (
                            guided_logits_rescaled * current_guidance_rescale
                            + guided_logits * (1.0 - current_guidance_rescale)
                        )

                    # Column normalization
                    logits = F.log_softmax(guided_logits, dim=-1)

                if classifier_fn is not None and classifier_scale > 0.0:
                    if classifier_schedule == "linear":
                        current_classifier_scale = classifier_scale * (1.0 - step_ratio)
                    elif classifier_schedule == "cosine":
                        current_classifier_scale = classifier_scale * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif classifier_schedule == "exponential":
                        current_classifier_scale = classifier_scale * math.exp(-3.0 * step_ratio)
                    elif classifier_schedule == "cyclic":
                        current_classifier_scale = classifier_scale * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                    else:
                        current_classifier_scale = classifier_scale

                    current_classifier_scale = max(current_classifier_scale, min_classifier_scale)

                    with torch.enable_grad():
                        logits_with_grad = logits.detach().requires_grad_(True)
                        classifier_score = classifier_fn(logits_with_grad, x, current_timesteps)
                        grads = torch.autograd.grad(classifier_score.sum(), logits_with_grad)[0]

                    logits = logits + current_classifier_scale * grads

                if suppress_tokens is not None:
                    logits[:, :, suppress_tokens] = -float("Inf")

                if begin_suppress_tokens is not None and block_start == T:
                    logits[:, 0, begin_suppress_tokens] = -float("Inf")

                if logit_bias is not None:
                    for token_id, bias in logit_bias.items():
                        logits[:, :, token_id] += bias

                if current_top_k > 0:
                    top_k_val = min(max(current_top_k, 1), logits.size(-1))
                    indices_to_remove = logits < torch.topk(logits, top_k_val, dim=-1)[0][..., -1, None]
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if no_repeat_ngram_size > 0:
                    for b in range(batch_size):
                        seq = x[b, :block_end]
                        for pos in range(block_start, block_end):
                            if pos < no_repeat_ngram_size - 1:
                                continue

                            prev_tokens = seq[pos - (no_repeat_ngram_size - 1):pos]
                            if mask_id not in prev_tokens:
                                prefix_list = prev_tokens.tolist()
                                banned_tokens = set()

                                for start_idx in range(pos - no_repeat_ngram_size + 1):
                                    window = seq[start_idx:start_idx + no_repeat_ngram_size - 1].tolist()
                                    if window == prefix_list:
                                        next_token = seq[start_idx + no_repeat_ngram_size - 1].item()
                                        if next_token != mask_id:
                                            banned_tokens.add(next_token)

                                if banned_tokens:
                                    for bt in banned_tokens:
                                        logits[b, pos, bt] = -float("Inf")

                if encoder_no_repeat_ngram_size > 0:
                    for b in range(batch_size):
                        seq = x[b, :block_end]
                        prompt_seq = x[b, :T]
                        for pos in range(block_start, block_end):
                            if pos < encoder_no_repeat_ngram_size - 1:
                                continue

                            prev_tokens = seq[pos - (encoder_no_repeat_ngram_size - 1):pos]
                            if mask_id not in prev_tokens:
                                prefix_list = prev_tokens.tolist()
                                banned_tokens = set()

                                # Search only within the prompt
                                for start_idx in range(T - encoder_no_repeat_ngram_size + 1):
                                    window = prompt_seq[start_idx:start_idx + encoder_no_repeat_ngram_size - 1].tolist()
                                    if window == prefix_list:
                                        next_token = prompt_seq[start_idx + encoder_no_repeat_ngram_size - 1].item()
                                        if next_token != mask_id:
                                            banned_tokens.add(next_token)

                                if banned_tokens:
                                    for bt in banned_tokens:
                                        logits[b, pos, bt] = -float("Inf")

                if ngram_penalty != 1.0 and ngram_size > 0:
                    for b in range(batch_size):
                        seq = x[b, :block_end]
                        for pos in range(block_start, block_end):
                            if pos < ngram_size - 1:
                                continue

                            prev_tokens = seq[pos - (ngram_size - 1):pos]
                            if mask_id not in prev_tokens:
                                prefix_list = prev_tokens.tolist()
                                counts: dict[int, int] = {}

                                for start_idx in range(pos - ngram_size + 1):
                                    window = seq[start_idx:start_idx + ngram_size - 1].tolist()
                                    if window == prefix_list:
                                        next_token = seq[start_idx + ngram_size - 1].item()
                                        if next_token != mask_id:
                                            counts[next_token] = counts.get(next_token, 0) + 1

                                for tok, count in counts.items():
                                    score = logits[b, pos, tok]
                                    penalty_factor = ngram_penalty ** count
                                    penalized_score = torch.where(
                                        score < 0,
                                        score * penalty_factor,
                                        score / penalty_factor
                                    )
                                    logits[b, pos, tok] = penalized_score

                if bad_words_ids is not None:
                    for b in range(batch_size):
                        for pos in range(block_start, block_end):
                            for bad_word in bad_words_ids:
                                if not bad_word:
                                    continue
                                if len(bad_word) == 1:
                                    logits[b, pos, bad_word[0]] = -float("Inf")
                                else:
                                    prefix_len = len(bad_word) - 1
                                    if pos >= prefix_len:
                                        prev_tokens = x[b, pos - prefix_len : pos]
                                        if mask_id not in prev_tokens:
                                            if prev_tokens.tolist() == bad_word[:-1]:
                                                logits[b, pos, bad_word[-1]] = -float("Inf")

                current_repetition_penalty = repetition_penalty
                if repetition_penalty != 1.0 and repetition_penalty_schedule != "constant":
                    if repetition_penalty_schedule == "linear":
                        current_repetition_penalty = repetition_penalty * (1.0 - step_ratio)
                    elif repetition_penalty_schedule == "cosine":
                        current_repetition_penalty = repetition_penalty * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif repetition_penalty_schedule == "exponential":
                        current_repetition_penalty = repetition_penalty * math.exp(-3.0 * step_ratio)
                    elif repetition_penalty_schedule == "cyclic":
                        current_repetition_penalty = repetition_penalty * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                current_repetition_penalty = max(current_repetition_penalty, min_repetition_penalty)

                current_frequency_penalty = frequency_penalty
                if frequency_penalty != 0.0 and frequency_penalty_schedule != "constant":
                    if frequency_penalty_schedule == "linear":
                        current_frequency_penalty = frequency_penalty * (1.0 - step_ratio)
                    elif frequency_penalty_schedule == "cosine":
                        current_frequency_penalty = frequency_penalty * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif frequency_penalty_schedule == "exponential":
                        current_frequency_penalty = frequency_penalty * math.exp(-3.0 * step_ratio)
                    elif frequency_penalty_schedule == "cyclic":
                        current_frequency_penalty = frequency_penalty * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                current_frequency_penalty = max(current_frequency_penalty, min_frequency_penalty)

                current_presence_penalty = presence_penalty
                if presence_penalty != 0.0 and presence_penalty_schedule != "constant":
                    if presence_penalty_schedule == "linear":
                        current_presence_penalty = presence_penalty * (1.0 - step_ratio)
                    elif presence_penalty_schedule == "cosine":
                        current_presence_penalty = presence_penalty * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif presence_penalty_schedule == "exponential":
                        current_presence_penalty = presence_penalty * math.exp(-3.0 * step_ratio)
                    elif presence_penalty_schedule == "cyclic":
                        current_presence_penalty = presence_penalty * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                current_presence_penalty = max(current_presence_penalty, min_presence_penalty)

                if (current_repetition_penalty != 1.0 or current_frequency_penalty != 0.0 or
                    current_presence_penalty != 0.0 or encoder_repetition_penalty != 1.0 or
                    encoder_frequency_penalty != 0.0 or encoder_presence_penalty != 0.0):
                    # Apply penalties to already generated/unmasked tokens
                    for b in range(batch_size):
                        # Get tokens in the context (ignoring mask tokens)
                        context_tokens = x[b, :block_end]
                        valid_context = context_tokens[context_tokens != mask_id]
                        if penalty_range is not None and penalty_range > 0:
                            valid_context = valid_context[-penalty_range:]

                        if valid_context.numel() > 0:
                            unique_tokens, counts = torch.unique(valid_context, return_counts=True)

                            if current_repetition_penalty != 1.0:
                                score = logits[b, :, unique_tokens]
                                penalized_score = torch.where(score < 0, score * current_repetition_penalty, score / current_repetition_penalty)
                                logits[b, :, unique_tokens] = penalized_score

                            if current_frequency_penalty != 0.0 or current_presence_penalty != 0.0:
                                # presence_penalty applies once if the token is present
                                # frequency_penalty applies proportionally to the count
                                penalty = (current_presence_penalty + counts.float() * current_frequency_penalty).unsqueeze(0)
                                logits[b, :, unique_tokens] -= penalty.to(logits.device)

                        if encoder_repetition_penalty != 1.0 or encoder_frequency_penalty != 0.0 or encoder_presence_penalty != 0.0:
                            prompt_tokens = x[b, :T]
                            valid_prompt_tokens = prompt_tokens[prompt_tokens != mask_id]

                            if len(valid_prompt_tokens) > 0:
                                unique_prompt_tokens, counts = torch.unique(valid_prompt_tokens, return_counts=True)

                                if encoder_repetition_penalty != 1.0:
                                    score = logits[b, :, unique_prompt_tokens]
                                    penalized_score = torch.where(
                                        score < 0,
                                        score * encoder_repetition_penalty,
                                        score / encoder_repetition_penalty
                                    )
                                    logits[b, :, unique_prompt_tokens] = penalized_score

                                if encoder_frequency_penalty != 0.0 or encoder_presence_penalty != 0.0:
                                    penalty = (encoder_presence_penalty + counts.float() * encoder_frequency_penalty).unsqueeze(0)
                                    logits[b, :, unique_prompt_tokens] -= penalty.to(logits.device)

                if min_new_tokens is not None and min_new_tokens > 0 and eos_token_id is not None:
                    # current generated tokens count is block_start - T
                    # min_new_tokens requirement means block_start + (generated inside block)
                    # For simplicity in block generation, we just disable eos_token if we haven't reached min_new_tokens.
                    if block_end - T <= min_new_tokens:
                        if isinstance(eos_token_id, list):
                            for eos_id in eos_token_id:
                                logits[:, :, eos_id] = -float("Inf")
                        else:
                            logits[:, :, eos_token_id] = -float("Inf")

                current_length_penalty = length_penalty
                if length_penalty != 1.0 and eos_token_id is not None:
                    if length_penalty_schedule == "linear":
                        current_length_penalty = length_penalty * (1.0 - step_ratio) + 1.0 * step_ratio
                    elif length_penalty_schedule == "cosine":
                        current_length_penalty = 1.0 + (length_penalty - 1.0) * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif length_penalty_schedule == "exponential":
                        current_length_penalty = 1.0 + (length_penalty - 1.0) * math.exp(-3.0 * step_ratio)
                    elif length_penalty_schedule == "cyclic":
                        current_length_penalty = 1.0 + (length_penalty - 1.0) * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    if isinstance(current_length_penalty, float):
                        current_length_penalty = max(current_length_penalty, min_length_penalty) if length_penalty > 1.0 else min(current_length_penalty, min_length_penalty)

                    if current_length_penalty != 1.0:
                        eos_ids = eos_token_id if isinstance(eos_token_id, list) else [eos_token_id]
                        for eos_id in eos_ids:
                            score = logits[:, :, eos_id]
                            score = torch.where(
                                score < 0, score * current_length_penalty, score / current_length_penalty
                            )
                            logits[:, :, eos_id] = score

                current_top_n_tokens = top_n_tokens
                if top_n_tokens > 0:
                    if top_n_tokens_schedule == "linear":
                        current_top_n_tokens = int(top_n_tokens * (1.0 - step_ratio))
                    elif top_n_tokens_schedule == "cosine":
                        current_top_n_tokens = int(top_n_tokens * 0.5 * (1.0 + math.cos(math.pi * step_ratio)))
                    elif top_n_tokens_schedule == "exponential":
                        current_top_n_tokens = int(top_n_tokens * math.exp(-3.0 * step_ratio))
                    elif top_n_tokens_schedule == "cyclic":
                        current_top_n_tokens = int(top_n_tokens * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio)))

                    current_top_n_tokens = max(current_top_n_tokens, min_top_n_tokens)

                if current_top_n_tokens > 0:
                    vocab_size = logits.size(-1)
                    if current_top_n_tokens < vocab_size:
                        top_n_values, top_n_indices = torch.topk(logits, current_top_n_tokens, dim=-1)
                        min_top_n_values = top_n_values[..., -1:]
                        logits = torch.where(logits < min_top_n_values, torch.full_like(logits, -float("Inf")), logits)

                current_xtc_threshold = xtc_threshold
                if xtc_threshold > 0.0:
                    if xtc_threshold_schedule == "linear":
                        current_xtc_threshold = xtc_threshold * (1.0 - step_ratio)
                    elif xtc_threshold_schedule == "cosine":
                        current_xtc_threshold = xtc_threshold * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif xtc_threshold_schedule == "exponential":
                        current_xtc_threshold = xtc_threshold * math.exp(-3.0 * step_ratio)
                    elif xtc_threshold_schedule == "cyclic":
                        current_xtc_threshold = xtc_threshold * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                    current_xtc_threshold = max(current_xtc_threshold, min_xtc_threshold)

                current_xtc_probability = xtc_probability
                if xtc_probability > 0.0:
                    if xtc_probability_schedule == "linear":
                        current_xtc_probability = xtc_probability * (1.0 - step_ratio)
                    elif xtc_probability_schedule == "cosine":
                        current_xtc_probability = xtc_probability * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif xtc_probability_schedule == "exponential":
                        current_xtc_probability = xtc_probability * math.exp(-3.0 * step_ratio)
                    elif xtc_probability_schedule == "cyclic":
                        current_xtc_probability = xtc_probability * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))
                    current_xtc_probability = max(current_xtc_probability, min_xtc_probability)

                if current_xtc_probability > 0.0 and current_xtc_threshold > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs, max_indices = probs.max(dim=-1, keepdim=True)

                    # Create a mask for tokens exceeding the threshold
                    exceeds_threshold = max_probs > current_xtc_threshold

                    # Generate random numbers for each token position
                    random_probs = torch.rand_like(max_probs)

                    # Mask for applying XTC
                    apply_xtc = exceeds_threshold & (random_probs < current_xtc_probability)

                    # We need to set the logit of the top token to -inf where apply_xtc is True
                    # Create a scatter mask
                    batch_size, seq_len, _ = logits.shape

                    # Expand apply_xtc to match logits shape for scatter
                    apply_xtc_expanded = apply_xtc.expand(-1, -1, logits.size(-1))

                    # Create a mask that is True only at the max_indices
                    top_token_mask = torch.zeros_like(logits, dtype=torch.bool).scatter_(-1, max_indices, True)

                    # Combine the masks
                    xtc_mask = top_token_mask & apply_xtc_expanded

                    logits = logits.masked_fill(xtc_mask, -float("Inf"))

                current_top_p = top_p
                if top_p < 1.0:
                    if top_p_schedule == "linear":
                        current_top_p = top_p * (1.0 - step_ratio)
                    elif top_p_schedule == "cosine":
                        current_top_p = top_p * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif top_p_schedule == "exponential":
                        current_top_p = top_p * math.exp(-3.0 * step_ratio)
                    elif top_p_schedule == "cyclic":
                        current_top_p = top_p * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_top_p = max(current_top_p, min_top_p)

                if current_top_p < 1.0:
                    sorted_logits, sorted_indices = torch.sort(logits, descending=True, dim=-1)
                    cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)

                    # Remove tokens with cumulative probability above the threshold
                    sorted_indices_to_remove = cumulative_probs > current_top_p
                    # Shift the indices to the right to keep also the first token above the threshold
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_min_p = min_p
                if min_p > 0.0:
                    if min_p_schedule == "linear":
                        current_min_p = min_p * (1.0 - step_ratio)
                    elif min_p_schedule == "cosine":
                        current_min_p = min_p * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif min_p_schedule == "exponential":
                        current_min_p = min_p * math.exp(-3.0 * step_ratio)
                    elif min_p_schedule == "cyclic":
                        current_min_p = min_p * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_min_p = max(current_min_p, min_min_p)

                if current_min_p > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs = probs.max(dim=-1, keepdim=True).values
                    indices_to_remove = probs < (current_min_p * max_probs)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_top_a = top_a
                if top_a > 0.0:
                    if top_a_schedule == "linear":
                        current_top_a = top_a * (1.0 - step_ratio)
                    elif top_a_schedule == "cosine":
                        current_top_a = top_a * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif top_a_schedule == "exponential":
                        current_top_a = top_a * math.exp(-3.0 * step_ratio)
                    elif top_a_schedule == "cyclic":
                        current_top_a = top_a * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_top_a = max(current_top_a, min_top_a)

                if top_a > 0.0 and current_top_a > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs = probs.max(dim=-1, keepdim=True).values
                    limit = current_top_a * (max_probs ** 2)
                    indices_to_remove = probs < limit
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_epsilon = epsilon_cutoff
                if epsilon_cutoff > 0.0:
                    if epsilon_cutoff_schedule == "linear":
                        current_epsilon = epsilon_cutoff * (1.0 - step_ratio)
                    elif epsilon_cutoff_schedule == "cosine":
                        current_epsilon = epsilon_cutoff * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif epsilon_cutoff_schedule == "exponential":
                        current_epsilon = epsilon_cutoff * math.exp(-3.0 * step_ratio)
                    elif epsilon_cutoff_schedule == "cyclic":
                        current_epsilon = epsilon_cutoff * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_epsilon = max(current_epsilon, min_epsilon_cutoff)

                if current_epsilon > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    indices_to_remove = probs < current_epsilon
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_eta = eta_cutoff
                if eta_cutoff > 0.0:
                    if eta_cutoff_schedule == "linear":
                        current_eta = eta_cutoff * (1.0 - step_ratio)
                    elif eta_cutoff_schedule == "cosine":
                        current_eta = eta_cutoff * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif eta_cutoff_schedule == "exponential":
                        current_eta = eta_cutoff * math.exp(-3.0 * step_ratio)
                    elif eta_cutoff_schedule == "cyclic":
                        current_eta = eta_cutoff * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_eta = max(current_eta, min_eta_cutoff)

                if current_eta > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                    # min(eta_cutoff, sqrt(eta_cutoff) * exp(-entropy))
                    eta_tensor = torch.tensor(current_eta, device=logits.device, dtype=logits.dtype)
                    threshold = torch.minimum(
                        eta_tensor,
                        torch.sqrt(eta_tensor) * torch.exp(-entropy)
                    )
                    indices_to_remove = probs < threshold
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_tfs_z = tfs_z
                if tfs_z < 1.0 or min_tfs_z < 1.0:
                    if tfs_z_schedule == "linear":
                        current_tfs_z = tfs_z + (min_tfs_z - tfs_z) * step_ratio
                    elif tfs_z_schedule == "cosine":
                        current_tfs_z = min_tfs_z + (tfs_z - min_tfs_z) * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif tfs_z_schedule == "exponential":
                        # for tfs_z which usually goes towards 1.0 (less cutoff)
                        # or from 1.0 to tfs_z, we use a simple exp interpolation
                        current_tfs_z = min_tfs_z + (tfs_z - min_tfs_z) * math.exp(-3.0 * step_ratio)
                    elif tfs_z_schedule == "cyclic":
                        current_tfs_z = min_tfs_z + (tfs_z - min_tfs_z) * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    # Limit the value between min and max of (tfs_z, min_tfs_z)
                    current_tfs_z = max(min(current_tfs_z, max(tfs_z, min_tfs_z)), min(tfs_z, min_tfs_z))

                if (tfs_z < 1.0 or min_tfs_z < 1.0) and current_tfs_z < 1.0:
                    probs = F.softmax(logits, dim=-1)
                    sorted_probs, sorted_indices = torch.sort(probs, descending=True, dim=-1)

                    # Calculate first derivative (differences between consecutive probs)
                    # We pad the right side to keep the same shape
                    first_deriv = sorted_probs[..., :-1] - sorted_probs[..., 1:]

                    # Calculate second derivative (differences between consecutive first derivatives)
                    second_deriv = first_deriv[..., :-1] - first_deriv[..., 1:]

                    # Pad second derivative to match sequence length
                    # We pad with zeros at the end
                    pad_zeros = torch.zeros((*second_deriv.shape[:-1], 2), device=second_deriv.device, dtype=second_deriv.dtype)
                    second_deriv = torch.cat([second_deriv, pad_zeros], dim=-1)

                    # Calculate absolute second derivative and its cumulative sum
                    abs_second_deriv = torch.abs(second_deriv)

                    # Normalize by the sum of absolute second derivatives
                    sum_abs_second_deriv = torch.sum(abs_second_deriv, dim=-1, keepdim=True)
                    # Avoid division by zero
                    sum_abs_second_deriv = torch.clamp(sum_abs_second_deriv, min=1e-9)

                    normalized_second_deriv = abs_second_deriv / sum_abs_second_deriv
                    cumulative_probs = torch.cumsum(normalized_second_deriv, dim=-1)

                    # Remove tokens where cumulative normalized second derivative is > tfs_z
                    sorted_indices_to_remove = cumulative_probs > tfs_z

                    # Shift the indices to the right to keep also the first token above the threshold
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_typical_p = typical_p
                if typical_p < 1.0:
                    if typical_p_schedule == "linear":
                        current_typical_p = typical_p * (1.0 - step_ratio)
                    elif typical_p_schedule == "cosine":
                        current_typical_p = typical_p * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif typical_p_schedule == "exponential":
                        current_typical_p = typical_p * math.exp(-3.0 * step_ratio)
                    elif typical_p_schedule == "cyclic":
                        current_typical_p = typical_p * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    current_typical_p = max(current_typical_p, min_typical_p)

                if typical_p < 1.0 and current_typical_p < 1.0:
                    probs = F.softmax(logits, dim=-1)
                    entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                    shifted_entropy = torch.abs(-torch.log(probs + 1e-9) - entropy)

                    sorted_entropy, sorted_indices = torch.sort(shifted_entropy, descending=False, dim=-1)
                    sorted_probs = torch.gather(probs, -1, sorted_indices)
                    cumulative_probs = torch.cumsum(sorted_probs, dim=-1)

                    sorted_indices_to_remove = cumulative_probs > current_typical_p
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if logits_processor is not None:
                    logits = logits_processor(x, logits)

                current_temperature = temperature
                if temperature > 0 or dynamic_temperature_entropy > 0:
                    if temperature_schedule == "linear":
                        current_temperature = temperature * (1.0 - step_ratio)
                    elif temperature_schedule == "cosine":
                        current_temperature = temperature * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif temperature_schedule == "exponential":
                        current_temperature = temperature * math.exp(-3.0 * step_ratio)
                    elif temperature_schedule == "cyclic":
                        current_temperature = temperature * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                    if dynamic_temperature_entropy > 0.0:
                        current_dynamic_temperature_entropy = dynamic_temperature_entropy
                        if dynamic_temperature_entropy_schedule == "linear":
                            current_dynamic_temperature_entropy = dynamic_temperature_entropy * (1.0 - step_ratio)
                        elif dynamic_temperature_entropy_schedule == "cosine":
                            current_dynamic_temperature_entropy = dynamic_temperature_entropy * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                        elif dynamic_temperature_entropy_schedule == "exponential":
                            current_dynamic_temperature_entropy = dynamic_temperature_entropy * math.exp(-3.0 * step_ratio)
                        elif dynamic_temperature_entropy_schedule == "cyclic":
                            current_dynamic_temperature_entropy = dynamic_temperature_entropy * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                        current_dynamic_temperature_entropy = max(current_dynamic_temperature_entropy, min_dynamic_temperature_entropy)

                        probs = F.softmax(logits, dim=-1)
                        entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                        current_temperature = current_temperature + current_dynamic_temperature_entropy * entropy

                    # Handle case where current_temperature becomes a tensor (from entropy)
                    if isinstance(current_temperature, torch.Tensor):
                        current_temperature = torch.clamp(current_temperature, min=min_temperature)
                    else:
                        current_temperature = max(current_temperature, min_temperature)

                if temperature_mask is not None:
                    current_mask = temperature_mask[:, block_start:block_end]
                    current_temperature = current_temperature * current_mask

                # Gumbel temperature scheduling
                gumbel_t = gumbel_temperature if gumbel_temperature is not None else temperature
                current_gumbel_temperature = gumbel_t
                if gumbel_t > 0.0 and gumbel_temperature_schedule != "constant":
                    if gumbel_temperature_schedule == "linear":
                        current_gumbel_temperature = gumbel_t * (1.0 - step_ratio)
                    elif gumbel_temperature_schedule == "cosine":
                        current_gumbel_temperature = gumbel_t * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif gumbel_temperature_schedule == "exponential":
                        current_gumbel_temperature = gumbel_t * math.exp(-3.0 * step_ratio)
                    elif gumbel_temperature_schedule == "cyclic":
                        current_gumbel_temperature = gumbel_t * 0.5 * (1.0 + math.cos(2.0 * math.pi * step_ratio))

                if current_gumbel_temperature is not None and not isinstance(current_gumbel_temperature, torch.Tensor):
                    current_gumbel_temperature = max(current_gumbel_temperature, min_gumbel_temperature)

                if logit_smoothing > 0.0:
                    logits = logits * (1 - logit_smoothing) + logits.mean(dim=-1, keepdim=True) * logit_smoothing

                if renormalize_logits:
                    logits = logits - logits.logsumexp(dim=-1, keepdim=True)

                if return_dict_in_generate and output_scores:
                    scores.append(logits.clone())

                # Check if current_temperature is > 0 (can be a tensor or float)
                is_temp_positive = (current_gumbel_temperature > 0).any() if isinstance(current_gumbel_temperature, torch.Tensor) else (current_gumbel_temperature > 0)

                if is_temp_positive:
                    logits_f = logits.to(torch.float32)
                    noise = torch.rand_like(logits_f)
                    gumbel_noise = (-torch.log(noise.clamp(min=1e-9))) ** current_gumbel_temperature

                    # For masked items, logits is -inf, so exp() is 0. 0 / gumbel_noise is 0.
                    logits_with_noise = logits_f.exp() / gumbel_noise
                else:
                    logits_with_noise = logits

                x0 = torch.argmax(logits_with_noise, dim=-1)

                if hasattr(self, 'tokenizer') and self.tokenizer is not None:
                    x0 = filter_special_tokens(x0, self.tokenizer, mask_id)

                if remasking == 'low_confidence':
                    p = F.softmax(logits.to(torch.float64), dim=-1)
                    x0_p = torch.squeeze(
                        torch.gather(p, dim=-1, index=torch.unsqueeze(x0, -1)), -1)
                elif remasking == 'entropy':
                    p = F.softmax(logits.to(torch.float64), dim=-1)
                    entropy = -torch.sum(p * torch.log(p + 1e-9), dim=-1)
                    # Lower entropy means higher confidence
                    x0_p = -entropy
                elif remasking == 'random':
                    x0_p = torch.rand((x0.shape[0], x0.shape[1]), device=x0.device)
                else:
                    x0_p = torch.ones((x0.shape[0], x0.shape[1]), device=x0.device)

                x0_p[:, block_end:] = -np.inf
                x0 = torch.where(mask_index, x0, x)
                confidence = torch.where(mask_index, x0_p, -torch.tensor(np.inf, device=device))

                if unmasking_schedule == "entropy":
                    p_ent = F.softmax(logits.to(torch.float64), dim=-1)
                    ent_val = -torch.sum(p_ent * torch.log(p_ent + 1e-9), dim=-1)
                    max_ent = math.log(logits.size(-1)) if logits.size(-1) > 1 else 1.0
                    for b_idx in range(x.shape[0]):
                        curr_masks = mask_index[b_idx].sum().item()
                        remaining_steps = steps_per_block - i
                        if remaining_steps <= 1:
                            num_transfer_tokens[b_idx, i] = curr_masks
                        elif curr_masks == 0:
                            num_transfer_tokens[b_idx, i] = 0
                        else:
                            mean_ent = ent_val[b_idx][mask_index[b_idx]].mean().item()
                            norm_ent = mean_ent / max_ent
                            confidence_score = 1.0 - norm_ent
                            target_tokens = max(1, int(curr_masks * confidence_score))
                            linear_tokens = max(1, curr_masks // remaining_steps)
                            num_transfer_tokens[b_idx, i] = int((target_tokens + linear_tokens) / 2)

                if num_beams > 1:
                    next_beam_scores = torch.full((original_batch_size, num_beams * num_beams), -1e9, device=device)
                    next_beam_tokens = torch.zeros((original_batch_size, num_beams * num_beams, x.size(1)), dtype=x.dtype, device=device)

                    log_probs = F.log_softmax(logits, dim=-1)

                    for b_orig in range(original_batch_size):
                        for b_beam in range(num_beams):
                            b = b_orig * num_beams + b_beam
                            M = num_transfer_tokens[b, i].item()

                            if M > 0:
                                _, select_index = torch.topk(confidence[b], k=M)
                                branch_pos = select_index[-1]

                                greedy_score = 0.0
                                candidate_x = x[b].clone()
                                for pos in select_index[:-1]:
                                    tok = x0[b, pos]
                                    candidate_x[pos] = tok
                                    greedy_score += log_probs[b, pos, tok].item()

                                top_v, top_i = torch.topk(log_probs[b, branch_pos], k=num_beams)

                                for j in range(num_beams):
                                    cand_score = beam_scores[b].item() + greedy_score + top_v[j].item()
                                    cand_x = candidate_x.clone()
                                    cand_x[branch_pos] = top_i[j]

                                    idx = b_beam * num_beams + j
                                    next_beam_scores[b_orig, idx] = cand_score
                                    next_beam_tokens[b_orig, idx] = cand_x
                            else:
                                for j in range(num_beams):
                                    idx = b_beam * num_beams + j
                                    if j == 0:
                                        next_beam_scores[b_orig, idx] = beam_scores[b].item()
                                        next_beam_tokens[b_orig, idx] = x[b].clone()
                                    else:
                                        next_beam_scores[b_orig, idx] = -1e9
                                        next_beam_tokens[b_orig, idx] = x[b].clone()

                    top_scores, top_indices = torch.topk(next_beam_scores, k=num_beams, dim=-1)

                    for b_orig in range(original_batch_size):
                        for b_beam in range(num_beams):
                            b = b_orig * num_beams + b_beam
                            idx = top_indices[b_orig, b_beam]
                            beam_scores[b] = top_scores[b_orig, b_beam]
                            x[b] = next_beam_tokens[b_orig, idx]

                else:
                    transfer_index = torch.zeros_like(x0, dtype=torch.bool, device=device)
                    for j in range(confidence.shape[0]):
                        if num_transfer_tokens[j, i] > 0:
                            _, select_index = torch.topk(confidence[j], k=num_transfer_tokens[j, i])
                            transfer_index[j, select_index] = True

                    x[transfer_index] = x0[transfer_index].to(x.dtype)

            if stopping_criteria is not None and stopping_criteria(x, logits):
                break

            # Check for early stopping via eos_token_id
            if eos_token_id is not None:
                # Find sequences that generated eos_token_id in the current block
                if isinstance(eos_token_id, list):
                    eos_in_block = torch.stack([(x[:, block_start:block_end] == eos_id) for eos_id in eos_token_id]).any(dim=0)
                    finished_mask = torch.stack([(x[:, T:block_end] == eos_id) for eos_id in eos_token_id]).any(dim=0).any(dim=1)
                else:
                    eos_in_block = (x[:, block_start:block_end] == eos_token_id)
                    finished_mask = (x[:, T:block_end] == eos_token_id).any(dim=1)

                if eos_in_block.any():
                    # If all sequences in the batch have an eos_token_id in or before this block, stop
                    # A sequence is finished if it has an eos_token anywhere after T
                    if finished_mask.all():
                        # Truncate x up to block_end
                        x = x[:, :block_end]
                        break

        if num_beams > 1 and num_return_sequences <= num_beams:
            final_x = []
            for b_orig in range(original_batch_size):
                for b_return in range(num_return_sequences):
                    b = b_orig * num_beams + b_return
                    final_x.append(x[b])
            x = torch.stack(final_x, dim=0)

        # Process padding if eos_token_id and pad_token_id are provided
        if eos_token_id is not None and pad_token_id is not None:
            # batch_size may have changed if we filtered beams
            batch_size = x.size(0)
            for b in range(batch_size):
                # Find first eos_token_id after the prompt
                if isinstance(eos_token_id, list):
                    eos_indices = torch.stack([(x[b, T:] == eos_id) for eos_id in eos_token_id]).any(dim=0).nonzero(as_tuple=True)[0]
                else:
                    eos_indices = (x[b, T:] == eos_token_id).nonzero(as_tuple=True)[0]

                if len(eos_indices) > 0:
                    first_eos = eos_indices[0].item() + T
                    # Pad the rest of the sequence
                    x[b, first_eos + 1:] = pad_token_id

        if return_dict_in_generate:
            return {
                "sequences": x,
                "scores": tuple(scores) if output_scores else None
            }

        return x

    def generate_dynamic_batch(self, requests_configs: List[Dict[str, Any]], max_batch_size: int = 8) -> List[torch.Tensor]:
        """
        Processes a list of generation requests simultaneously using dynamic continuous batching.
        Each request configuration must contain at least 'input_ids' and 'max_new_tokens'.
        """
        manager = MDLMContinuousBatchingManager(self, max_batch_size=max_batch_size)

        request_ids = []
        for config in requests_configs:
            req_id = manager.add_request(**config)
            request_ids.append(req_id)

        while manager.active_requests or manager.pending_requests:
            manager.step()

        # Return results in the original order
        results = []
        completed_map = {req.request_id: req.result for req in manager.completed_requests}
        for req_id in request_ids:
            results.append(completed_map[req_id])

        return results

import uuid
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional

@dataclass
class MDLMRequest:
    input_ids: torch.Tensor
    max_new_tokens: int
    total_steps: int
    unmasking_schedule: str = "linear"
    temperature: float = 0.0
    request_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    current_step: int = 0
    x: Optional[torch.Tensor] = None
    mask_index: Optional[torch.Tensor] = None
    status: str = "pending"
    result: Optional[torch.Tensor] = None
    transfer_tokens: Optional[torch.Tensor] = None

class MDLMContinuousBatchingManager:
    """
    Manager for in-flight (continuous) batching with Masked Diffusion Language Models.
    Allows processing requests of different lengths and different diffusion step counts simultaneously.
    """
    def __init__(self, model: DiffusionModelForConditionalGeneration, max_batch_size: int = 8):
        self.model = model
        self.max_batch_size = max_batch_size
        self.pending_requests: List[MDLMRequest] = []
        self.active_requests: List[MDLMRequest] = []
        self.completed_requests: List[MDLMRequest] = []

    def add_request(self, input_ids: torch.Tensor, max_new_tokens: int, total_steps: int, **kwargs) -> str:
        req = MDLMRequest(input_ids=input_ids, max_new_tokens=max_new_tokens, total_steps=total_steps, **kwargs)
        self.pending_requests.append(req)
        return req.request_id

    @torch.no_grad()
    def step(self):
        # 1. Promote pending to active
        while len(self.active_requests) < self.max_batch_size and self.pending_requests:
            req = self.pending_requests.pop(0)
            device = req.input_ids.device
            mask_id = self.model.config.mask_token_id

            prompt_len = req.input_ids.size(1)
            x = torch.full((1, prompt_len + req.max_new_tokens), mask_id, dtype=req.input_ids.dtype, device=device)
            x[0, :prompt_len] = req.input_ids[0]

            req.x = x
            req.mask_index = (x == mask_id)
            req.transfer_tokens = get_num_transfer_tokens(req.mask_index, req.total_steps, schedule=req.unmasking_schedule)
            req.status = "active"
            self.active_requests.append(req)

        if not self.active_requests:
            return False

        # 2. Pad active requests to form a batch
        max_len = max(req.x.size(1) for req in self.active_requests)
        batch_x = []
        batch_attention_mask = []

        mask_id = self.model.config.mask_token_id

        for req in self.active_requests:
            pad_len = max_len - req.x.size(1)
            if pad_len > 0:
                padded_x = F.pad(req.x, (0, pad_len), value=mask_id)
                attn_mask = torch.cat([torch.ones(req.x.size(1), device=req.x.device), torch.zeros(pad_len, device=req.x.device)])
            else:
                padded_x = req.x
                attn_mask = torch.ones(req.x.size(1), device=req.x.device)
            batch_x.append(padded_x[0])
            batch_attention_mask.append(attn_mask)

        batch_x = torch.stack(batch_x)
        batch_attention_mask = torch.stack(batch_attention_mask)

        # 3. Compute timesteps
        t_ratios = []
        for req in self.active_requests:
            t_ratio = req.mask_index.sum().float() / req.x.size(1)
            t_ratios.append(t_ratio)
        t_ratios = torch.tensor(t_ratios, device=batch_x.device)
        current_timesteps = (t_ratios * self.model.config.max_timesteps).long().clamp(min=1, max=self.model.config.max_timesteps)

        # 4. Forward pass
        outputs = self.model(
            input_ids=batch_x,
            attention_mask=batch_attention_mask,
            timesteps=current_timesteps
        )
        logits = outputs.logits if hasattr(outputs, "logits") else outputs[0]

        # 5. Iterative unmasking per request
        finished_reqs = []
        for i, req in enumerate(self.active_requests):
            req_len = req.x.size(1)
            req_logits = logits[i:i+1, :req_len, :]

            M = req.transfer_tokens[0, req.current_step].item()

            if req.temperature > 0:
                req_logits = req_logits / req.temperature

            x0 = torch.argmax(req_logits, dim=-1)

            p = F.softmax(req_logits.to(torch.float64), dim=-1)
            x0_p = torch.squeeze(torch.gather(p, dim=-1, index=torch.unsqueeze(x0, -1)), -1)

            confidence = torch.where(req.x == mask_id, x0_p, -torch.tensor(float('inf'), device=req.x.device))

            if req.unmasking_schedule == "entropy":
                curr_masks = req.mask_index[0].sum().item()
                remaining_steps = req.total_steps - req.current_step
                if remaining_steps <= 1:
                    req.transfer_tokens[0, req.current_step] = curr_masks
                elif curr_masks == 0:
                    req.transfer_tokens[0, req.current_step] = 0
                else:
                    p_ent = F.softmax(req_logits.to(torch.float64), dim=-1)
                    ent_val = -torch.sum(p_ent * torch.log(p_ent + 1e-9), dim=-1)
                    max_ent = math.log(req_logits.size(-1)) if req_logits.size(-1) > 1 else 1.0
                    mean_ent = ent_val[0][req.mask_index[0]].mean().item()
                    norm_ent = mean_ent / max_ent
                    confidence_score = 1.0 - norm_ent
                    target_tokens = max(1, int(curr_masks * confidence_score))
                    linear_tokens = max(1, curr_masks // remaining_steps)
                    req.transfer_tokens[0, req.current_step] = int((target_tokens + linear_tokens) / 2)
                M = req.transfer_tokens[0, req.current_step].item()

            if M > 0:
                _, select_index = torch.topk(confidence[0], k=M)
                req.x[0, select_index] = x0[0, select_index].to(req.x.dtype)
                req.mask_index[0, select_index] = False

            req.current_step += 1

            if req.current_step >= req.total_steps:
                req.status = "completed"
                req.result = req.x
                finished_reqs.append(req)

        # 6. Remove finished
        for req in finished_reqs:
            self.active_requests.remove(req)
            self.completed_requests.append(req)

        return True


UniversalDiffusionLM = DiffusionModelForConditionalGeneration
UniversalDiffusionLM.register_for_auto_class("AutoModelForCausalLM")
UniversalDiffusionLM.register_for_auto_class("AutoModel")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModelForCausalLM")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModel")
