import torch
import torch.nn as nn
from transformers import PreTrainedModel, AutoConfig, AutoModel
import torch.nn.functional as F
from typing import Optional, Tuple, Union, List
import numpy as np

from .configuration_diffusion import DiffusionConfig

def get_num_transfer_tokens(mask_index, steps):
    """
    Compute the number of tokens to unmask at each step for each sequence in the batch.
    """
    mask_num = mask_index.sum(dim=1, keepdim=True)
    base = mask_num // steps
    remainder = mask_num % steps
    transfer_tokens = torch.zeros(mask_num.shape[0], steps, dtype=torch.long, device=mask_index.device)
    for i in range(steps):
        transfer_tokens[:, i] = base.squeeze() + (remainder.squeeze() > i).long()
    return transfer_tokens

def filter_special_tokens(tokens, tokenizer, mask_id):
    """
    Replace special tokens generated by the model with mask_id.
    """
    special_ids = [tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id]
    special_ids = [id for id in special_ids if id is not None]

    mask = torch.zeros_like(tokens, dtype=torch.bool)
    for special_id in special_ids:
        mask |= (tokens == special_id)

    tokens = torch.where(mask, torch.tensor(mask_id, device=tokens.device, dtype=tokens.dtype), tokens)
    return tokens

class DiffusionModelForConditionalGeneration(PreTrainedModel):
    config_class = DiffusionConfig

    def __init__(self, config: DiffusionConfig):
        super().__init__(config)

        base_config = AutoConfig.for_model(**config.base_config_dict)
        self.inner_model = AutoModel.from_config(base_config)
        self._disable_causal_mask()

        self.timestep_embedder = nn.Sequential(
            nn.Linear(1, config.timestep_dim),
            nn.SiLU(),
            nn.Linear(config.timestep_dim, base_config.hidden_size)
        )

        self.lm_head = nn.Linear(base_config.hidden_size, base_config.vocab_size, bias=False)

        if getattr(base_config, "tie_word_embeddings", False):
            self.lm_head.weight = self.inner_model.get_input_embeddings().weight

    def _disable_causal_mask(self):
        """
        Dynamic patching to disable causality.
        In transformers >= 5.9.0, masking is delegated to masking_utils which
        checks config.is_causal. Setting it to False allows fallback to
        bidirectional mask.
        For older models or specific implementations, further patching can be done.
        """
        if hasattr(self.inner_model, "config"):
            self.inner_model.config.is_causal = False

        # Additionally patch _update_causal_mask if present (from the example)
        if hasattr(self.inner_model, "_update_causal_mask"):
            self.inner_model._update_causal_mask = lambda *args, **kwargs: args[1] if len(args) > 1 else kwargs.get("attention_mask")

        if self.inner_model.config.model_type == "gpt2":
            for module in self.inner_model.modules():
                if hasattr(module, "bias") and isinstance(module.bias, torch.Tensor) and module.bias.dim() == 4:
                    module.bias.data.fill_(1)

    def get_input_embeddings(self):
        return self.inner_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.inner_model.set_input_embeddings(value)

    def forward(self, input_ids=None, timesteps=None, attention_mask=None, inputs_embeds=None, labels=None, **kwargs):
        if inputs_embeds is None:
            if input_ids is None:
                raise ValueError("You have to specify either input_ids or inputs_embeds")
            embeddings_layer = self.inner_model.get_input_embeddings()
            inputs_embeds = embeddings_layer(input_ids)

        if timesteps is not None:
            t_embed = self.timestep_embedder(timesteps.unsqueeze(-1).float())
            hidden_states = inputs_embeds + t_embed.unsqueeze(1)
        else:
            hidden_states = inputs_embeds

        outputs = self.inner_model(
            inputs_embeds=hidden_states,
            attention_mask=attention_mask,
            return_dict=True,
            **kwargs
        )

        logits = self.lm_head(outputs.last_hidden_state)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            # Shift so that tokens < n predict n - we don't do this for diffusion
            # Calculate loss only on positions where labels != -100 (which corresponds to masked positions)
            loss = loss_fct(logits.view(-1, self.config.base_config_dict.get('vocab_size', logits.size(-1))), labels.view(-1))

        if return_dict := kwargs.get('return_dict', True):
            from transformers.modeling_outputs import CausalLMOutputWithPast
            return CausalLMOutputWithPast(
                loss=loss,
                logits=logits,
                past_key_values=outputs.past_key_values if hasattr(outputs, "past_key_values") else None,
                hidden_states=outputs.hidden_states if hasattr(outputs, "hidden_states") else None,
                attentions=outputs.attentions if hasattr(outputs, "attentions") else None,
            )
        else:
            return tuple(v for v in [loss, logits] if v is not None)

    @torch.no_grad()
    def generate(
        self,
        input_ids: torch.Tensor,
        max_new_tokens: int = 128,
        steps: Optional[int] = None,
        block_length: Optional[int] = None,
        temperature: float = 0.0,
        cfg_scale: float = 0.0,
        remasking: Optional[str] = None,
        attention_mask: Optional[torch.Tensor] = None,
        **kwargs
    ):
        """
        Iterative unmasking generation for Diffusion Models.
        """
        steps = steps or self.config.diffusion_steps
        block_length = block_length or self.config.block_size
        remasking = remasking or self.config.remasking_strategy
        mask_id = self.config.mask_token_id

        if mask_id is None:
            raise ValueError("mask_token_id must be set in the configuration for generation.")

        T = input_ids.size(-1)
        batch_size = input_ids.size(0)
        device, dtype = input_ids.device, input_ids.dtype

        if max_new_tokens % block_length != 0:
            block_length = max_new_tokens

        num_blocks = max_new_tokens // block_length
        if steps % num_blocks != 0:
            steps_per_block = max(1, steps // num_blocks)
        else:
            steps_per_block = steps // num_blocks

        x = torch.full((batch_size, T + max_new_tokens), mask_id, dtype=dtype, device=device)
        x[:, :T] = input_ids

        for num_block in range(num_blocks):
            block_start = T + num_block * block_length
            block_end = T + (num_block + 1) * block_length

            block_mask_index = (x[:, block_start:block_end] == mask_id)
            num_transfer_tokens = get_num_transfer_tokens(block_mask_index, steps_per_block)

            for i in range(steps_per_block):
                mask_index = (x == mask_id)

                # We can supply timesteps if needed, but in basic sampling they are implicit or t=0 for unmasked
                # A simple approximation: timesteps is proportional to remaining masks
                t_ratio = mask_index.sum(dim=1).float() / (T + max_new_tokens)
                current_timesteps = (t_ratio * self.config.max_timesteps).long().clamp(min=1, max=self.config.max_timesteps)

                outputs = self(input_ids=x, attention_mask=attention_mask, timesteps=current_timesteps)
                logits = outputs.logits if hasattr(outputs, "logits") else outputs[0]

                if temperature > 0:
                    logits_f = logits.to(torch.float32)
                    noise = torch.rand_like(logits_f)
                    gumbel_noise = (-torch.log(noise)) ** temperature
                    logits_with_noise = logits_f.exp() / gumbel_noise
                else:
                    logits_with_noise = logits

                x0 = torch.argmax(logits_with_noise, dim=-1)

                if hasattr(self, 'tokenizer') and self.tokenizer is not None:
                    x0 = filter_special_tokens(x0, self.tokenizer, mask_id)

                if remasking == 'low_confidence':
                    p = F.softmax(logits.to(torch.float64), dim=-1)
                    x0_p = torch.squeeze(
                        torch.gather(p, dim=-1, index=torch.unsqueeze(x0, -1)), -1)
                elif remasking == 'random':
                    x0_p = torch.rand((x0.shape[0], x0.shape[1]), device=x0.device)
                else:
                    x0_p = torch.ones((x0.shape[0], x0.shape[1]), device=x0.device)

                x0_p[:, block_end:] = -np.inf
                x0 = torch.where(mask_index, x0, x)
                confidence = torch.where(mask_index, x0_p, -torch.tensor(np.inf, device=device))

                transfer_index = torch.zeros_like(x0, dtype=torch.bool, device=device)
                for j in range(confidence.shape[0]):
                    if num_transfer_tokens[j, i] > 0:
                        _, select_index = torch.topk(confidence[j], k=num_transfer_tokens[j, i])
                        transfer_index[j, select_index] = True

                x[transfer_index] = x0[transfer_index].to(x.dtype)

        return x

UniversalDiffusionLM = DiffusionModelForConditionalGeneration
UniversalDiffusionLM.register_for_auto_class("AutoModelForCausalLM")
UniversalDiffusionLM.register_for_auto_class("AutoModel")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModelForCausalLM")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModel")
