import torch
import torch.nn as nn
from transformers import PreTrainedModel, AutoConfig, AutoModel
import torch.nn.functional as F
from typing import Optional, Tuple, Union, List
import numpy as np
import time

from .configuration_diffusion import DiffusionConfig

def get_num_transfer_tokens(mask_index, steps):
    """
    Compute the number of tokens to unmask at each step for each sequence in the batch.
    """
    mask_num = mask_index.sum(dim=1, keepdim=True)
    base = mask_num // steps
    remainder = mask_num % steps
    transfer_tokens = torch.zeros(mask_num.shape[0], steps, dtype=torch.long, device=mask_index.device)
    for i in range(steps):
        transfer_tokens[:, i] = base.squeeze() + (remainder.squeeze() > i).long()
    return transfer_tokens

def filter_special_tokens(tokens, tokenizer, mask_id):
    """
    Replace special tokens generated by the model with mask_id.
    """
    special_ids = [tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id]
    special_ids = [id for id in special_ids if id is not None]

    mask = torch.zeros_like(tokens, dtype=torch.bool)
    for special_id in special_ids:
        mask |= (tokens == special_id)

    tokens = torch.where(mask, torch.tensor(mask_id, device=tokens.device, dtype=tokens.dtype), tokens)
    return tokens

class DiffusionModelForConditionalGeneration(PreTrainedModel):
    config_class = DiffusionConfig

    def __init__(self, config: DiffusionConfig):
        super().__init__(config)

        base_config = AutoConfig.for_model(**config.base_config_dict)
        self.inner_model = AutoModel.from_config(base_config)
        self._disable_causal_mask()

        self.timestep_embedder = nn.Sequential(
            nn.Linear(1, config.timestep_dim),
            nn.SiLU(),
            nn.Linear(config.timestep_dim, base_config.hidden_size)
        )

        self.lm_head = nn.Linear(base_config.hidden_size, base_config.vocab_size, bias=False)

        if getattr(base_config, "tie_word_embeddings", False):
            self.lm_head.weight = self.inner_model.get_input_embeddings().weight

    def _disable_causal_mask(self):
        """
        Dynamic patching to disable causality.
        In transformers >= 5.9.0, masking is delegated to masking_utils which
        checks config.is_causal. Setting it to False allows fallback to
        bidirectional mask.
        For older models or specific implementations, further patching can be done.
        """
        if hasattr(self.inner_model, "config"):
            self.inner_model.config.is_causal = False

        # Additionally patch _update_causal_mask if present (from the example)
        if hasattr(self.inner_model, "_update_causal_mask"):
            self.inner_model._update_causal_mask = lambda *args, **kwargs: args[1] if len(args) > 1 else kwargs.get("attention_mask")

        if self.inner_model.config.model_type == "gpt2":
            for module in self.inner_model.modules():
                if hasattr(module, "bias") and isinstance(module.bias, torch.Tensor) and module.bias.dim() == 4:
                    module.bias.data.fill_(1)


    def get_steering_vector(self, positive_input_ids, negative_input_ids, layer_name, attention_mask=None):
        captured_states = []

        def hook(module, input, output):
            if isinstance(output, tuple):
                captured_states.append(output[0].detach())
            else:
                captured_states.append(output.detach())

        target_layer = dict(self.inner_model.named_modules()).get(layer_name)
        if target_layer is None:
            raise ValueError(f"Layer {layer_name} not found in inner_model")

        handle = target_layer.register_forward_hook(hook)

        try:
            self.forward(input_ids=positive_input_ids, attention_mask=attention_mask)
            self.forward(input_ids=negative_input_ids, attention_mask=attention_mask)
        finally:
            handle.remove()

        if len(captured_states) != 2:
            raise RuntimeError("Failed to capture hidden states for both forward passes.")

        positive_mean = captured_states[0].mean(dim=1)
        negative_mean = captured_states[1].mean(dim=1)

        return positive_mean - negative_mean

    def get_input_embeddings(self):
        return self.inner_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.inner_model.set_input_embeddings(value)

    def forward(self, input_ids=None, timesteps=None, attention_mask=None, inputs_embeds=None, labels=None, steering_vector=None, steering_layer_name=None, steering_scale=1.0, **kwargs):
        if inputs_embeds is None:
            if input_ids is None:
                raise ValueError("You have to specify either input_ids or inputs_embeds")
            embeddings_layer = self.inner_model.get_input_embeddings()
            inputs_embeds = embeddings_layer(input_ids)

        if timesteps is not None:
            t_embed = self.timestep_embedder(timesteps.unsqueeze(-1).float())
            hidden_states = inputs_embeds + t_embed.unsqueeze(1)
        else:
            hidden_states = inputs_embeds

        handle = None
        if steering_vector is not None and steering_layer_name is not None:
            target_layer = dict(self.inner_model.named_modules()).get(steering_layer_name)
            if target_layer is not None:
                def steer_hook(module, input, output):
                    steer = steering_scale * steering_vector.unsqueeze(1) # shape (batch, 1, hidden)
                    if isinstance(output, tuple):
                        return tuple([output[0] + steer] + list(output[1:]))
                    return output + steer
                handle = target_layer.register_forward_hook(steer_hook)

        try:
            inner_kwargs = kwargs.copy()
            if 'return_dict' in inner_kwargs:
                del inner_kwargs['return_dict']
            outputs = self.inner_model(
                inputs_embeds=hidden_states,
                attention_mask=attention_mask,
                return_dict=True,
                **inner_kwargs
            )
        finally:
            if handle is not None:
                handle.remove()

        logits = self.lm_head(outputs.last_hidden_state)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            # Shift so that tokens < n predict n - we don't do this for diffusion
            # Calculate loss only on positions where labels != -100 (which corresponds to masked positions)
            loss = loss_fct(logits.view(-1, self.config.base_config_dict.get('vocab_size', logits.size(-1))), labels.view(-1))

        if return_dict := kwargs.get('return_dict', True):
            from transformers.modeling_outputs import CausalLMOutputWithPast
            return CausalLMOutputWithPast(
                loss=loss,
                logits=logits,
                past_key_values=outputs.past_key_values if hasattr(outputs, "past_key_values") else None,
                hidden_states=outputs.hidden_states if hasattr(outputs, "hidden_states") else None,
                attentions=outputs.attentions if hasattr(outputs, "attentions") else None,
            )
        else:
            return tuple(v for v in [loss, logits] if v is not None)

    @torch.no_grad()
    def generate(
        self,
        input_ids: torch.Tensor,
        max_new_tokens: int = 128,
        steps: Optional[int] = None,
        block_length: Optional[int] = None,
        temperature: float = 0.0,
        temperature_schedule: str = "constant",
        min_temperature: float = 0.0,
        cfg_scale: float = 0.0,
        cfg_schedule: str = "constant",
        guidance_rescale: float = 0.0,
        top_k: int = 0,
        top_p: float = 1.0,
        min_p: float = 0.0,
        typical_p: float = 1.0,
        typical_p_schedule: str = "constant",
        min_typical_p: float = 0.0,
        top_a: float = 0.0,
        epsilon_cutoff: float = 0.0,
        eta_cutoff: float = 0.0,
        tfs_z: float = 1.0,
        dynamic_temperature_entropy: float = 0.0,
        repetition_penalty: float = 1.0,
        frequency_penalty: float = 0.0,
        presence_penalty: float = 0.0,
        xtc_threshold: float = 0.0,
        xtc_probability: float = 0.0,
        min_new_tokens: Optional[int] = None,
        no_repeat_ngram_size: int = 0,
        bad_words_ids: Optional[list[list[int]]] = None,
        max_time: Optional[float] = None,
        remove_invalid_values: bool = False,
        logit_bias: Optional[dict[int, float]] = None,
        suppress_tokens: Optional[list[int]] = None,
        remasking: Optional[str] = None,
        attention_mask: Optional[torch.Tensor] = None,
        unconditional_input_ids: Optional[torch.Tensor] = None,
        steering_vector: Optional[torch.Tensor] = None,
        steering_layer_name: Optional[str] = None,
        steering_scale: float = 1.0,
        eos_token_id: Optional[int] = None,
        pad_token_id: Optional[int] = None,
        forced_decoder_ids: Optional[list[list[int]]] = None,
        forced_eos_token_id: Optional[int] = None,
        renormalize_logits: bool = False,
        **kwargs
    ):
        """
        Iterative unmasking generation for Diffusion Models.
        """
        start_time = time.time() if max_time is not None else None

        steps = steps or self.config.diffusion_steps
        block_length = block_length or self.config.block_size
        remasking = remasking or self.config.remasking_strategy
        mask_id = self.config.mask_token_id

        if mask_id is None:
            raise ValueError("mask_token_id must be set in the configuration for generation.")

        T = input_ids.size(-1)
        batch_size = input_ids.size(0)
        device, dtype = input_ids.device, input_ids.dtype

        if max_new_tokens % block_length != 0:
            block_length = max_new_tokens

        num_blocks = max_new_tokens // block_length
        if steps % num_blocks != 0:
            steps_per_block = max(1, steps // num_blocks)
        else:
            steps_per_block = steps // num_blocks

        x = torch.full((batch_size, T + max_new_tokens), mask_id, dtype=dtype, device=device)
        x[:, :T] = input_ids

        if forced_decoder_ids is not None:
            for forced_id in forced_decoder_ids:
                if len(forced_id) == 2:
                    idx, token = forced_id
                    if 0 <= idx < max_new_tokens:
                        x[:, T + idx] = token

        if forced_eos_token_id is not None:
            x[:, T + max_new_tokens - 1] = forced_eos_token_id

        for num_block in range(num_blocks):
            if max_time is not None and time.time() - start_time > max_time:
                break

            block_start = T + num_block * block_length
            block_end = T + (num_block + 1) * block_length

            block_mask_index = (x[:, block_start:block_end] == mask_id)
            num_transfer_tokens = get_num_transfer_tokens(block_mask_index, steps_per_block)

            for i in range(steps_per_block):
                if max_time is not None and time.time() - start_time > max_time:
                    break

                step_ratio = i / max(1, steps_per_block - 1) if steps_per_block > 1 else 0.0

                mask_index = (x == mask_id)

                # We can supply timesteps if needed, but in basic sampling they are implicit or t=0 for unmasked
                # A simple approximation: timesteps is proportional to remaining masks
                t_ratio = mask_index.sum(dim=1).float() / (T + max_new_tokens)
                current_timesteps = (t_ratio * self.config.max_timesteps).long().clamp(min=1, max=self.config.max_timesteps)

                outputs = self(
                    input_ids=x,
                    attention_mask=attention_mask,
                    timesteps=current_timesteps,
                    steering_vector=steering_vector,
                    steering_layer_name=steering_layer_name,
                    steering_scale=steering_scale
                )
                logits = outputs.logits if hasattr(outputs, "logits") else outputs[0]

                if remove_invalid_values:
                    # set all nan values to 0.0
                    logits = torch.where(logits != logits, 0.0, logits)
                    # set all +/-inf values to max/min possible value
                    logits = torch.where(logits == float("inf"), torch.finfo(logits.dtype).max, logits)
                    logits = torch.where(logits == -float("inf"), torch.finfo(logits.dtype).min, logits)

                if cfg_scale > 0.0 and unconditional_input_ids is not None:
                    if cfg_schedule == "linear":
                        current_cfg_scale = cfg_scale * (1.0 - step_ratio)
                    elif cfg_schedule == "cosine":
                        import math
                        current_cfg_scale = cfg_scale * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif cfg_schedule == "exponential":
                        import math
                        current_cfg_scale = cfg_scale * math.exp(-3.0 * step_ratio)
                    else:
                        current_cfg_scale = cfg_scale

                    uncond_x = x.clone()
                    # Replace the conditional prefix with unconditional prefix
                    # Assume unconditional_input_ids length <= T
                    uncond_len = unconditional_input_ids.size(1)
                    uncond_x[:, :uncond_len] = unconditional_input_ids
                    # If uncond_len < T, we might want to pad it with mask_id or leave original,
                    # standard CFG assumes same sequence length prefix

                    uncond_outputs = self(
                        input_ids=uncond_x,
                        attention_mask=attention_mask,
                        timesteps=current_timesteps,
                        steering_vector=steering_vector,
                        steering_layer_name=steering_layer_name,
                        steering_scale=steering_scale
                    )
                    uncond_logits = uncond_outputs.logits if hasattr(uncond_outputs, "logits") else uncond_outputs[0]

                    guided_logits = uncond_logits + current_cfg_scale * (logits - uncond_logits)

                    if guidance_rescale > 0.0:
                        std_logits = logits.std(dim=-1, keepdim=True)
                        std_guided_logits = guided_logits.std(dim=-1, keepdim=True)
                        # Fix out of bounds if standard deviation is exactly 0 to avoid NaNs
                        std_guided_logits = torch.where(std_guided_logits > 0, std_guided_logits, torch.ones_like(std_guided_logits))

                        guided_logits_rescaled = guided_logits * (std_logits / std_guided_logits)
                        guided_logits = (
                            guided_logits_rescaled * guidance_rescale
                            + guided_logits * (1.0 - guidance_rescale)
                        )

                    # Column normalization
                    logits = F.log_softmax(guided_logits, dim=-1)

                if suppress_tokens is not None:
                    logits[:, :, suppress_tokens] = -float("Inf")

                if logit_bias is not None:
                    for token_id, bias in logit_bias.items():
                        logits[:, :, token_id] += bias

                if top_k > 0:
                    top_k_val = min(max(top_k, 1), logits.size(-1))
                    indices_to_remove = logits < torch.topk(logits, top_k_val, dim=-1)[0][..., -1, None]
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if no_repeat_ngram_size > 0:
                    for b in range(batch_size):
                        seq = x[b, :block_end]
                        for pos in range(block_start, block_end):
                            if pos < no_repeat_ngram_size - 1:
                                continue

                            prev_tokens = seq[pos - (no_repeat_ngram_size - 1):pos]
                            if mask_id not in prev_tokens:
                                prefix_list = prev_tokens.tolist()
                                banned_tokens = set()

                                for start_idx in range(pos - no_repeat_ngram_size + 1):
                                    window = seq[start_idx:start_idx + no_repeat_ngram_size - 1].tolist()
                                    if window == prefix_list:
                                        next_token = seq[start_idx + no_repeat_ngram_size - 1].item()
                                        if next_token != mask_id:
                                            banned_tokens.add(next_token)

                                if banned_tokens:
                                    for bt in banned_tokens:
                                        logits[b, pos, bt] = -float("Inf")

                if bad_words_ids is not None:
                    for b in range(batch_size):
                        for pos in range(block_start, block_end):
                            for bad_word in bad_words_ids:
                                if not bad_word:
                                    continue
                                if len(bad_word) == 1:
                                    logits[b, pos, bad_word[0]] = -float("Inf")
                                else:
                                    prefix_len = len(bad_word) - 1
                                    if pos >= prefix_len:
                                        prev_tokens = x[b, pos - prefix_len : pos]
                                        if mask_id not in prev_tokens:
                                            if prev_tokens.tolist() == bad_word[:-1]:
                                                logits[b, pos, bad_word[-1]] = -float("Inf")

                if repetition_penalty != 1.0 or frequency_penalty != 0.0 or presence_penalty != 0.0:
                    # Apply penalties to already generated/unmasked tokens
                    for b in range(batch_size):
                        # Get tokens in the context (ignoring mask tokens)
                        context_tokens = x[b, :block_end]
                        valid_context = context_tokens[context_tokens != mask_id]

                        if valid_context.numel() > 0:
                            unique_tokens, counts = torch.unique(valid_context, return_counts=True)

                            if repetition_penalty != 1.0:
                                score = logits[b, :, unique_tokens]
                                penalized_score = torch.where(score < 0, score * repetition_penalty, score / repetition_penalty)
                                logits[b, :, unique_tokens] = penalized_score

                            if frequency_penalty != 0.0 or presence_penalty != 0.0:
                                # presence_penalty applies once if the token is present
                                # frequency_penalty applies proportionally to the count
                                penalty = (presence_penalty + counts.float() * frequency_penalty).unsqueeze(0)
                                logits[b, :, unique_tokens] -= penalty.to(logits.device)

                if min_new_tokens is not None and min_new_tokens > 0 and eos_token_id is not None:
                    # current generated tokens count is block_start - T
                    # min_new_tokens requirement means block_start + (generated inside block)
                    # For simplicity in block generation, we just disable eos_token if we haven't reached min_new_tokens.
                    if block_end - T <= min_new_tokens:
                        logits[:, :, eos_token_id] = -float("Inf")

                if xtc_probability > 0.0 and xtc_threshold > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs, max_indices = probs.max(dim=-1, keepdim=True)

                    # Create a mask for tokens exceeding the threshold
                    exceeds_threshold = max_probs > xtc_threshold

                    # Generate random numbers for each token position
                    random_probs = torch.rand_like(max_probs)

                    # Mask for applying XTC
                    apply_xtc = exceeds_threshold & (random_probs < xtc_probability)

                    # We need to set the logit of the top token to -inf where apply_xtc is True
                    # Create a scatter mask
                    batch_size, seq_len, _ = logits.shape

                    # Expand apply_xtc to match logits shape for scatter
                    apply_xtc_expanded = apply_xtc.expand(-1, -1, logits.size(-1))

                    # Create a mask that is True only at the max_indices
                    top_token_mask = torch.zeros_like(logits, dtype=torch.bool).scatter_(-1, max_indices, True)

                    # Combine the masks
                    xtc_mask = top_token_mask & apply_xtc_expanded

                    logits = logits.masked_fill(xtc_mask, -float("Inf"))

                if top_p < 1.0:
                    sorted_logits, sorted_indices = torch.sort(logits, descending=True, dim=-1)
                    cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)

                    # Remove tokens with cumulative probability above the threshold
                    sorted_indices_to_remove = cumulative_probs > top_p
                    # Shift the indices to the right to keep also the first token above the threshold
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if min_p > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs = probs.max(dim=-1, keepdim=True).values
                    indices_to_remove = probs < (min_p * max_probs)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if top_a > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    max_probs = probs.max(dim=-1, keepdim=True).values
                    limit = top_a * (max_probs ** 2)
                    indices_to_remove = probs < limit
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if epsilon_cutoff > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    indices_to_remove = probs < epsilon_cutoff
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if eta_cutoff > 0.0:
                    probs = F.softmax(logits, dim=-1)
                    entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                    # min(eta_cutoff, sqrt(eta_cutoff) * exp(-entropy))
                    eta_tensor = torch.tensor(eta_cutoff, device=logits.device, dtype=logits.dtype)
                    threshold = torch.minimum(
                        eta_tensor,
                        torch.sqrt(eta_tensor) * torch.exp(-entropy)
                    )
                    indices_to_remove = probs < threshold
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                if tfs_z < 1.0:
                    probs = F.softmax(logits, dim=-1)
                    sorted_probs, sorted_indices = torch.sort(probs, descending=True, dim=-1)

                    # Calculate first derivative (differences between consecutive probs)
                    # We pad the right side to keep the same shape
                    first_deriv = sorted_probs[..., :-1] - sorted_probs[..., 1:]

                    # Calculate second derivative (differences between consecutive first derivatives)
                    second_deriv = first_deriv[..., :-1] - first_deriv[..., 1:]

                    # Pad second derivative to match sequence length
                    # We pad with zeros at the end
                    pad_zeros = torch.zeros((*second_deriv.shape[:-1], 2), device=second_deriv.device, dtype=second_deriv.dtype)
                    second_deriv = torch.cat([second_deriv, pad_zeros], dim=-1)

                    # Calculate absolute second derivative and its cumulative sum
                    abs_second_deriv = torch.abs(second_deriv)

                    # Normalize by the sum of absolute second derivatives
                    sum_abs_second_deriv = torch.sum(abs_second_deriv, dim=-1, keepdim=True)
                    # Avoid division by zero
                    sum_abs_second_deriv = torch.clamp(sum_abs_second_deriv, min=1e-9)

                    normalized_second_deriv = abs_second_deriv / sum_abs_second_deriv
                    cumulative_probs = torch.cumsum(normalized_second_deriv, dim=-1)

                    # Remove tokens where cumulative normalized second derivative is > tfs_z
                    sorted_indices_to_remove = cumulative_probs > tfs_z

                    # Shift the indices to the right to keep also the first token above the threshold
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_typical_p = typical_p
                if typical_p < 1.0:
                    if typical_p_schedule == "linear":
                        current_typical_p = typical_p * (1.0 - step_ratio)
                    elif typical_p_schedule == "cosine":
                        import math
                        current_typical_p = typical_p * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif typical_p_schedule == "exponential":
                        import math
                        current_typical_p = typical_p * math.exp(-3.0 * step_ratio)

                    current_typical_p = max(current_typical_p, min_typical_p)

                if typical_p < 1.0 and current_typical_p < 1.0:
                    probs = F.softmax(logits, dim=-1)
                    entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                    shifted_entropy = torch.abs(-torch.log(probs + 1e-9) - entropy)

                    sorted_entropy, sorted_indices = torch.sort(shifted_entropy, descending=False, dim=-1)
                    sorted_probs = torch.gather(probs, -1, sorted_indices)
                    cumulative_probs = torch.cumsum(sorted_probs, dim=-1)

                    sorted_indices_to_remove = cumulative_probs > current_typical_p
                    sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                    sorted_indices_to_remove[..., 0] = 0

                    indices_to_remove = sorted_indices_to_remove.scatter(-1, sorted_indices, sorted_indices_to_remove)
                    logits = logits.masked_fill(indices_to_remove, -float("Inf"))

                current_temperature = temperature
                if temperature > 0 or dynamic_temperature_entropy > 0:
                    if temperature_schedule == "linear":
                        current_temperature = temperature * (1.0 - step_ratio)
                    elif temperature_schedule == "cosine":
                        import math
                        current_temperature = temperature * 0.5 * (1.0 + math.cos(math.pi * step_ratio))
                    elif temperature_schedule == "exponential":
                        import math
                        current_temperature = temperature * math.exp(-3.0 * step_ratio)

                    if dynamic_temperature_entropy > 0.0:
                        probs = F.softmax(logits, dim=-1)
                        entropy = -torch.sum(probs * torch.log(probs + 1e-9), dim=-1, keepdim=True)
                        current_temperature = current_temperature + dynamic_temperature_entropy * entropy

                    # Handle case where current_temperature becomes a tensor (from entropy)
                    if isinstance(current_temperature, torch.Tensor):
                        current_temperature = torch.clamp(current_temperature, min=min_temperature)
                    else:
                        current_temperature = max(current_temperature, min_temperature)

                if renormalize_logits:
                    logits = logits - logits.logsumexp(dim=-1, keepdim=True)

                # Check if current_temperature is > 0 (can be a tensor or float)
                is_temp_positive = (current_temperature > 0).any() if isinstance(current_temperature, torch.Tensor) else (current_temperature > 0)

                if is_temp_positive:
                    logits_f = logits.to(torch.float32)
                    noise = torch.rand_like(logits_f)
                    gumbel_noise = (-torch.log(noise.clamp(min=1e-9))) ** current_temperature

                    # For masked items, logits is -inf, so exp() is 0. 0 / gumbel_noise is 0.
                    logits_with_noise = logits_f.exp() / gumbel_noise
                else:
                    logits_with_noise = logits

                x0 = torch.argmax(logits_with_noise, dim=-1)

                if hasattr(self, 'tokenizer') and self.tokenizer is not None:
                    x0 = filter_special_tokens(x0, self.tokenizer, mask_id)

                if remasking == 'low_confidence':
                    p = F.softmax(logits.to(torch.float64), dim=-1)
                    x0_p = torch.squeeze(
                        torch.gather(p, dim=-1, index=torch.unsqueeze(x0, -1)), -1)
                elif remasking == 'random':
                    x0_p = torch.rand((x0.shape[0], x0.shape[1]), device=x0.device)
                else:
                    x0_p = torch.ones((x0.shape[0], x0.shape[1]), device=x0.device)

                x0_p[:, block_end:] = -np.inf
                x0 = torch.where(mask_index, x0, x)
                confidence = torch.where(mask_index, x0_p, -torch.tensor(np.inf, device=device))

                transfer_index = torch.zeros_like(x0, dtype=torch.bool, device=device)
                for j in range(confidence.shape[0]):
                    if num_transfer_tokens[j, i] > 0:
                        _, select_index = torch.topk(confidence[j], k=num_transfer_tokens[j, i])
                        transfer_index[j, select_index] = True

                x[transfer_index] = x0[transfer_index].to(x.dtype)

            # Check for early stopping via eos_token_id
            if eos_token_id is not None:
                # Find sequences that generated eos_token_id in the current block
                eos_in_block = (x[:, block_start:block_end] == eos_token_id)
                if eos_in_block.any():
                    # If all sequences in the batch have an eos_token_id in or before this block, stop
                    # A sequence is finished if it has an eos_token anywhere after T
                    finished_mask = (x[:, T:block_end] == eos_token_id).any(dim=1)
                    if finished_mask.all():
                        # Truncate x up to block_end
                        x = x[:, :block_end]
                        break

        # Process padding if eos_token_id and pad_token_id are provided
        if eos_token_id is not None and pad_token_id is not None:
            for b in range(batch_size):
                # Find first eos_token_id after the prompt
                eos_indices = (x[b, T:] == eos_token_id).nonzero(as_tuple=True)[0]
                if len(eos_indices) > 0:
                    first_eos = eos_indices[0].item() + T
                    # Pad the rest of the sequence
                    x[b, first_eos + 1:] = pad_token_id

        return x

UniversalDiffusionLM = DiffusionModelForConditionalGeneration
UniversalDiffusionLM.register_for_auto_class("AutoModelForCausalLM")
UniversalDiffusionLM.register_for_auto_class("AutoModel")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModelForCausalLM")
DiffusionModelForConditionalGeneration.register_for_auto_class("AutoModel")
